name: Tests & Coverage 🧪

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: book_loop
        ports:
          - 5446:5432
        options: >-
          --health-cmd "pg_isready -U app -d book_loop"
          --health-interval 5s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: stable
          check-latest: true
          cache-dependency-path: go.sum

      - name: Tidy
        run: go mod tidy

      - name: Build & Vet
        run: |
          go build ./...
          go vet ./...

      - name: Install migrate
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.0/migrate.linux-amd64.tar.gz \
          | tar -xz
          sudo mv migrate /usr/local/bin/

#      - name: Run migrations
#        run: |
#          migrate \
#            -path migrations/server \
#            -database "postgres://app:pass@localhost:5446/book_loop?sslmode=disable" \
#            up

      - name: Tests + Coverage
        env:
          TEST_DB_DSN: postgres://app:pass@localhost:5446/book_loop?sslmode=disable
        run: |
          go test -tags=integration $(go list ./... | grep -vE '/cmd/|/internal/docs') \
            -coverprofile=coverage.out.mocks \
            -covermode=atomic
          grep -vE "mock\.go|_mock\.go" coverage.out.mocks > coverage.out

      - name: Race detector
        env:
          TEST_DB_DSN: postgres://app:pass@localhost:5446/book_loop?sslmode=disable
        run: |
          go test -race -tags=integration $(go list ./... | grep -vE '/cmd/|/internal/docs')

      - name: Coverage summary
        run: |
          go tool cover -func=coverage.out | tail -n 1

      - name: Coverage → Cobertura
        run: |
          go install github.com/t-yuki/gocover-cobertura@latest
          "$(go env GOPATH)/bin/gocover-cobertura" < coverage.out > coverage.xml

      - name: Coverage report
        if: github.event_name == 'pull_request'
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml
          badge: true
          format: markdown
          output: both
          thresholds: "65 70"

      - name: Comment coverage in PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          recreate: true
          path: code-coverage-results.md

      - name: Get coverage value
        id: coverage
        run: |
          TOTAL=$(go tool cover -func=coverage.out | grep total | awk '{print $3}' | tr -d '%')
          echo "total=$TOTAL" >> "$GITHUB_OUTPUT"

      - name: Generate coverage badge
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          npm install -g badgen-cli

          COV=${{ steps.coverage.outputs.total }}
          
          COLOR=$(
          COV="$COV" node -p '
          const c = Number(process.env.COV);
          c >= 70 ? "green" :
          c >= 60 ? "yellow" :
          c >= 50 ? "orange" :
            "red"
            '
          )

          mkdir -p badges

          COV="$COV" badgen \
            -j coverage \
            -s "${COV}%" \
            -c "$COLOR" \
            > badges/coverage.svg

      - name: Publish badge
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./badges
          publish_branch: badges
          keep_files: true
          commit_message: "chore(badges): update coverage"